# Generated by Django 5.0.6 on 2024-06-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('stopovers', models.BooleanField(default=False)),
                ('specialOffer', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('stopovers', models.BooleanField(default=False)),
                ('specialOffer', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('stopovers', models.BooleanField(default=False)),
                ('specialOffer', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=400)),
            ],
        ),
    ]
