# Generated by Django 5.0.6 on 2024-06-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruise',
            old_name='airline',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='airline',
            new_name='company',
        ),
    ]
